### PR TITLE
Adding named Converters

### PR DESCRIPTION
**Pull request by adamclifford**
Checks to see if the converter is an object and there are named
converters on that object.

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
@adamclifford I was wondering if you'd been able to look at my comments?

**Comment by ErikSchierboom** [comment]
@adamclifford Bump

**Comment by adamclifford** [comment]
Hi @ErikSchierboom,
Sorry about not getting onto this. I'll hopefully get a chance to look at this at some point this weekend.

Adam

**Comment by ErikSchierboom** [comment]
@adamclifford No problem! It was just a small reminder.

**Comment by ErikSchierboom** [comment]
@adamclifford Another bump

**Comment by ErikSchierboom** [comment]
I'm going to close this due to lack of activity. If you do decide you want to work on this again, let me know!

**Pull request closed without merging**
